### ISSUE TITLE
MultiThreading Bug

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#24]
Im branch bug/multi2, test_optimize with at least 3 threads, sometimes the second solve_all call does not give any answer.

**Comment by rkaminsk** [comment]
I can reproduce the bug with the `PropagateControl` object wrapped. Somehow, I cannot reproduce it with the `PropagateInit` object wrapped but get get other test failures. I think something fishy is happening in this case because in theory it should be 100% transparent.

**Comment by rkaminsk** [comment]
You can just put the wrapping after the point where the check mode is set. Then it works. It is because I did not overwrite the item setters. also there is no point in taking a lock in `init()` because it is not called concurrently.

**Comment by rkaminsk** [comment]
Take a look at 96b0b7ff927296636b5137782baac2031e5c722d. Now we just have to write out the trace. The code for this is in my old lookahead bug branch.

**Comment by rkaminsk** [comment]
There is no bug in clasp. The bug is in your code. You tagged the wrong clauses. It is crucial to tag the lbs clause. The other clauses don't need to be tagged; that is taken care of at the point where you set `num_guess=1`. You can just have a look at the output of `python reproduce.py`, then you see that the second solve call correctly returns unsatisfiable.

**Comment by rkaminsk** [comment]
I fixed the bug in your minimize branch. Please don't delete the `bug/multi2` branch yet. I want to reuse the code look into the `bug/multi` problem.
